enum ValidationErrorType {
  blank,
  eightCharacters,
  oneSpecial,
  oneUppercase,
  oneDigit,
  mustNotContainEmail,
  wrongPassword,
  notLikeOldPassword,
  invalidProvider,
  userNotFound,
  userAlreadyExists,
  invalidEmail,
  emailAlreadyExist,
  phoneNumberAlreadyExist,
  incorrectCode,
  mismatchConfirmPassword,
  suggestedPriceTooHigh,
  wrongPasswordOrLogin,
  invalidPhone,
  unknown,
  endDateValidation,
}

